export const mockData = [
  // Sample data for testing
  {
    id: "1",
    name: "Product A",
    value: 1200,
    category: "Electronics",
    region: "North America",
    date: "2025-01-15",
  },
  {
    id: "2",
    name: "Product B",
    value: 850,
    category: "Furniture",
    region: "Europe",
    date: "2025-01-16",
  },
  {
    id: "3",
    name: "Product C",
    value: 2100,
    category: "Electronics",
    region: "Asia",
    date: "2025-01-17",
  },
  {
    id: "4",
    name: "Product D",
    value: 1500,
    category: "Clothing",
    region: "North America",
    date: "2025-01-18",
  },
  {
    id: "5",
    name: "Product E",
    value: 950,
    category: "Furniture",
    region: "North America",
    date: "2025-01-19",
  },
  {
    id: "6",
    name: "Product F",
    value: 1800,
    category: "Electronics",
    region: "Europe",
    date: "2025-01-20",
  },
  {
    id: "7",
    name: "Product G",
    value: 1100,
    category: "Clothing",
    region: "Asia",
    date: "2025-01-21",
  },
  {
    id: "8",
    name: "Product H",
    value: 2200,
    category: "Furniture",
    region: "Asia",
    date: "2025-01-22",
  },
  {
    id: "9",
    name: "Product I",
    value: 1400,
    category: "Clothing",
    region: "Europe",
    date: "2025-01-23",
  },
  {
    id: "10",
    name: "Product J",
    value: 1650,
    category: "Electronics",
    region: "North America",
    date: "2025-01-24",
  },
]
